#!/bin/sh -e

action="$1"
oldversion="$2"

umask 022

if [ "$action" != configure ]
  then
  exit 0
fi

fix_dir_perms(){
    chown www-data /var/cache/plug-ugmm/templates_c
    chmod 700 /var/cache/plug-ugmm/templates_c
}

clear_template_cache(){
    find /var/cache/plug-ugmm/templates_c -type f -exec rm -r {} \;
}

#DEBHELPER#

fix_dir_perms

clear_template_cache


exit 0
